---
name: Bug Report
description: File a bug report to address an issue in LSP-mdita-marksman.

body:
  - type: textarea
    attributes:
      label: Description of the bug
      description: |
        A description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps on how the bug can be reproduced. Make sure that the issue is with LSP-mdita-marksman and not with the language server itself. If it is with the language server, then the appropriate place to file an issue is at https://github.com/aireilly/mdita-marksman.
      placeholder: |
        1. First step.
        2. Second step.
        3. Third step.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: A description of what actually happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Troubleshooting information from LSP
      description: Run "LSP Troubleshoot server" from the command palette and select "LSP-mdita-marksman" from the options. Copy the contents here.
    validations:
      required: true

  - type: input
    attributes:
      label: LSP-mdita-marksman version
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: input
    attributes:
      label: mdita-marksman binary version
      description: Run "mdita-marksman --version" in your terminal.
      placeholder: "e.g. 1.0.0"
    validations:
      required: true
