---
name: Enhancement or feature request
description: File an enhancement or feature request to improve LSP-mdita-marksman.

body:
  - type: textarea
    attributes:
      label: Description of your enhancement or feature request
      description: |
        A description of what enhancement or feature you would like to see in LSP-mdita-marksman.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        What other alternatives currently exist that you are employing.
    validations:
      required: true
